CREATE TABLE INVERSIONESAPP.INV_USUARIOS_PORTAFOLIOS
(
    idUsuarioPortafolio NUMBER,
    idUsuario NUMBER UNIQUE,
    idPortafolio NUMBER UNIQUE,
    Num_montoInvertido NUMBER(*,2),
    Est_inactivo VARCHAR2(1)
)TABLESPACE TS_INVERSIONES

--Creación del sinónimo de la tabla para consultas
CREATE SYNONYM USU_PORTA FOR INVERSIONESAPP.INV_USUARIOS_PORTAFOLIOS;

--Creación de constraints
ALTER TABLE INVERSIONESAPP.INV_USUARIOS_PORTAFOLIOS ADD CONSTRAINT PK_USU_PORTA PRIMARY KEY(idUsuarioPortafolio);
--Foreign key a Usuarios
ALTER TABLE INVERSIONESAPP.INV_USUARIOS_PORTAFOLIOS 
ADD CONSTRAINT FK_USU_PORTA_USUAR FOREIGN KEY (idUsuario) REFERENCES INVERSIONESAPP.INV_USUARIOS (idUsuario);
--Foreign key a Portafolios
ALTER TABLE INVERSIONESAPP.INV_USUARIOS_PORTAFOLIOS 
ADD CONSTRAINT FK_USU_PORTA_PORTAF FOREIGN KEY (idPortafolio) REFERENCES INVERSIONESAPP.INV_PORTAFOLIOS (idPortafolio);

COMMENT ON TABLE INVERSIONESAPP.INV_USUARIOS_PORTAFOLIOS IS 'Almacena los datos de la inversión de un usuario en un portafolio';
COMMENT ON COLUMN INVERSIONESAPP.INV_USUARIOS_PORTAFOLIOS.Est_inactivo IS 
'Almacena el estado de activación del portafolio, por defecto inactivo(I), activo(A)';