CREATE TABLE INVERSIONESAPP.INV_PORTAFOLIOS_ACTIVOS
(
    idPortafolioActivo NUMBER,
    idPortafolio NUMBER UNIQUE,
    idActivo NUMBER UNIQUE
)TABLESPACE TS_INVERSIONES

--Creación del sinónimo de la tabla para consultas
CREATE SYNONYM PORTAF_ACTIVS FOR INVERSIONESAPP.INV_ACTIVOS;

--Creación de constraints
ALTER TABLE INVERSIONESAPP.INV_PORTAFOLIOS_ACTIVOS ADD CONSTRAINT PK_PORTAF_ACTIVS PRIMARY KEY (idPortafolioActivo);
--Foreign key  portafolios
ALTER TABLE INVERSIONESAPP.INV_PORTAFOLIOS_ACTIVOS ADD CONSTRAINT FK_PORTAF_ACTIVS_PORTAF FOREIGN KEY (idPortafolio)
REFERENCES INVERSIONESAPP.INV_PORTAFOLIOS (idPortafolio);
--Foreign key activos
ALTER TABLE INVERSIONESAPP.INV_PORTAFOLIOS_ACTIVOS ADD CONSTRAINT FK_PORTAF_ACTIVS_ACTIVS FOREIGN KEY (idActivo)
REFERENCES INVERSIONESAPP.INV_ACTIVOS (idActivo);

COMMENT ON TABLE INVERSIONESAPP.INV_PORTAFOLIOS_ACTIVOS IS 'Almacena la relación de los activos que pertenecen a cada portafolio';
