CREATE TABLE INVERSIONESAPP.INV_CIUDADES
(
    idCiudad NUMBER,
    Desc_nombre VARCHAR2(20)
)TABLESPACE TS_INVERSIONES

--Creación del sinónimo de la tabla para consultas
CREATE SYNONYM CIUDAD FOR INVERSIONESAPP.INV_CIUDADES;

--Creación de constraints
ALTER TABLE INVERSIONESAPP.INV_CIUDADES ADD CONSTRAINT PK_CIUDAD PRIMARY KEY(idCiudad);

COMMENT ON TABLE INVERSIONESAPP.INV_CIUDADES IS 'Almacena las ciudades para mostrar en el aplicativo';


