CREATE TABLE INVERSIONESAPP.INV_USUARIOS
(
   idUsuario NUMBER,
   Usr_nombre VARCHAR2(25),
   Usr_apellido VARCHAR2(25),
   Usr_correo VARCHAR(25),
   Usr_contrasena VARCHAR(20),
   Usr_documento VARCHAR(15),
   Fec_ingreso DATE default SYSDATE,
   idCiudad NUMBER UNIQUE
)TABLESPACE TS_INVERSIONES

--Creación del sinónimo de la tabla para consultas
CREATE SYNONYM USUAR FOR INVERSIONESAPP.INV_USUARIOS;

--Creación de constraints
ALTER TABLE INVERSIONESAPP.INV_USUARIOS ADD CONSTRAINT PK_USUAR PRIMARY KEY(idUsuario);
ALTER TABLE INVERSIONESAPP.INV_USUARIOS ADD CONSTRAINT FK_USUAR_CIUDAD FOREIGN KEY (idCiudad) REFERENCES INVERSIONESAPP.INV_CIUDADES (idCiudad);

COMMENT ON TABLE INVERSIONESAPP.INV_USUARIOS IS 'Registra los datos de los usuarios';
COMMENT ON COLUMN INVERSIONESAPP.INV_USUARIOS.Fec_ingreso IS 'Fecha de ingreso a la compañía de inversión (DD/MM/YY)';


