--Creación de esquema, permisos
CREATE USER INVERSIONESAPP IDENTIFIED BY admin;
GRANT CONNECT, RESOURCE TO INVERSIONESAPP;

--Creación de tablespace
CREATE TABLESPACE TS_INVERSIONES
DATAFILE 'C:/DATAFILE'
SIZE 100M
AUTOEXTEND ON NEXT 10M
MAXSIZE 2G;

